apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgress-deployment
  labels:
    name: postgress-deployment
    app: voting-app

spec:
  replicas: 1
  selector:
      matchLabels:
        name: postgres-pod
        app: voting-app
  template:
    metadata:
      name: db
      labels:
          name: postgres-pod
          app: voting-app
    spec:
        containers:
          - name: postgres
            image: postgres
            env:
              - name: POSTGRES_USER
                value: "postgres"
              - name: POSTGRES_PASSWORD
                value: "postgres"
            ports:
              - containerPort: 5432